project:
  type: website

website:
  title: "Spatialists – geospatial news"
  site-url: https://spatialists.ch
  description: "A blog for geospatial professionals"
  favicon: assets/favicon.png
  image: assets/titlecard.jpg
  twitter-card: true
  open-graph: true
  navbar:
    right: 
      - text: About
        href: about.qmd
      - text: Subscribe
        href: subscribe.qmd
      - text: Follow
        href: follow.qmd
      - text: Contribute
        href: contribute.qmd

  search:
    location: navbar
    type: overlay

format:
  html:
    theme: superhero
    css: styles.css
    include-in-header:
      - file: mailerlite-newsletter-form-code.html
      - file: mastodon-verification-code.html
      - file: matomo-statistics-code.html

execute:
  freeze: auto