---
title: "Follow the RSS feed"
image: false
about:
  template: solana
---

Follow Spatialists through the RSS feed using this address: 

<https://spatialists.ch/index.xml>

<br><br>

## What is an RSS feed?

An RSS feed contains the latest content of this site in a form that a 
feedreader app understands. Tons of websites already have feeds, mostly news 
sites and blogs.

Whenever you see a website with a feed, that means you can subscribe to that 
site using a feedreader app. The feedreader checks the feeds you have 
subscribed to automatically from time to time. If you subscribe to only one 
site, you might say "This doesn’t save me much time over occasionally checking 
that site myself." But if you end up subscribing to a dozen or more sites, 
you’ll find that your feedreader becomes *the* place for news.

## What is great about RSS feeds?

Using RSS, you won’t miss content and there won't be spam. RSS provides you 
with a non-algorithmic timeline of the content that interests you – unlike 
modern social media platforms.

## How do I get a feedreader app?

There are many different options to choose from. Wikipedia has an [overview of 
feedreaders](https://en.wikipedia.org/wiki/Comparison_of_feed_aggregators). 
Personally, I use [Feedly](https://feedly.com). It can be used in a browser or 
as native app on mobile.

## How do I subscribe to a feed?

You need the URL of the feed. Some feedreaders also have built-in methods to 
try and find a feed, given only the website URL. 

If you want to follow Spatialists, copy the address of its feed, 
<https://spatialists.ch/index.xml>, and add it to the subscriptions in your 
feedreader app. To achieve this, usually, you paste the address after having 
pressed a button "Add Feed", "Add Content", "Subscribe" or in the search 
function of the app.

You’re done! You can now read the latest Spatialists content in your feedreader!

