name: FeedBot
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  rss-to-mastodon:
    runs-on: ubuntu-latest
    steps:
      - name: Generate cache key
        uses: actions/github-script@v6
        id: generate-key
        with:
          script: |
            core.setOutput('cache-key', new Date().valueOf())
      - name: Retrieve cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/mastofeedbot
          key: feed-cache-${{ steps.generate-key.outputs.cache-key }}
          restore-keys: feed-cache-
      - name: GitHub
        uses: 'joschi/mastofeedbot@v1'
        with:
          # This is the RSS feed you want to publish
          rss-feed: https://spatialists.ch/index.xml
          # Template of status posted to Mastodon (Handlebars)
          template: |
            {{item.title}}: {{item.description}}            
            {{item.link}} #GIS #GISchat #geospatial #SwissGIS
          # Visibility of the posted status (public | unlisted | private | direct)
          status-visibility: private
          # Mark Mastodon status as sensitive content
          sensitive: false
          # This is your instance address
          api-endpoint: https://mapstodon.space
          # This is the secret you created earlier
          api-token: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          # This is a path to the cache file, using the above cache path
          cache-file: ${{ github.workspace }}/mastofeedbot/cache.json
          # The maximum number of posts created on the first run
          initial-post-limit: 1
